### ISSUE TITLE
_md-icon.scss

### ISSUE THREAD

**Issue by bluehenry** [BHP-DevHub/bhp-ui#1]
Hi 

_md-icon.scss need import material-design-icons package. 

> @import '~material-design-icons/iconfont/material-icons.css';

So users have to either install material-design-icons or exclude _md-icon.scss, other than will get an error.

**Comment by mbertolacci** [comment]
Hi Henry,

Yes, that's right `material-design-icons` is a peer dependency of this package and must be installed alongside it. I will update the README.md to reflect this.

Mike
